# Generated by Django 5.0.4 on 2024-04-19 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_options_articletags_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='articles',
        ),
    ]
